cache:
  - file: multirepo-backend-sample/go.sum
    path: .gopath
services:
  frontend:
    runtime: reactjs
    port: 3000
    build:
      - ls
  backend:
    runtime: go
    port: 8080
    build:
      - go mod download
      - go build .
    serve:
      - ./multirepo-backend-sample
    environment:
      GOPATH: /local/.gopath
