cache:
  - file: multirepo-frontend-sample/yarn.lock
    path: multirepo-frontend-sample/.yarn-cache
  - file: multirepo-backend-sample/go.sum
    path: .gopath
services:
  frontend:
    runtime: reactjs
    port: 3000
    path: multirepo-frontend-sample
    build:
      - yarn config set cache-folder $(pwd)/.yarn-cache
      - yarn install --frozen-lockfile
    serve:
      - yarn start
    environment:
      HOST: 0.0.0.0
      CI: true
  backend:
    runtime: go
    port: 8080
    path: multirepo-backend-sample
    build:
      - go mod download
      - go build .
    serve:
      - ./multirepo-backend-sample
    environment:
      GOPATH: /local/.gopath
